name: outliers-football
channels:
  - anaconda
  - conda-forge
dependencies:
  - jupyter
  - pandas
  - seaborn
  - pyarrow
  - beautifulsoup4
  - requests
  - scikit-learn
  - lxml
  - pillow
  - openpyxl
  - fuzzywuzzy
  - metaphone
  - pip
  - pip:
      - mplsoccer
      - shap      
      - adjustText
      - fuzzymatcher
      
